Vagrant.configure("2") do |config|
  # Detect host CPU
  host_cpu = RbConfig::CONFIG['host_cpu']

  if host_cpu =~ /arm|aarch64/
    # Mac ARM
    config.vm.box = "spox/ubuntu-arm"
    config.vm.box_version = "1.0.0"
  else
    # Windows x86_64
    config.vm.box = "ubuntu/jammy64"
    config.vm.box_version = "20241002.0.0"
  end

  # Shared network config
  config.vm.network "private_network", ip: "192.168.56.11"

  # VMware provider config
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
  end
end
