Vagrant.configure("2") do |config|
  # Detect host CPU
  host_cpu = RbConfig::CONFIG['host_cpu']

  if host_cpu =~ /arm|aarch64/
    # Mac ARM host
    config.vm.box = "bandit145/centos_stream9_arm"
  else
    # Windows (x86_64) host
    config.vm.box = "eurolinux-vagrant/centos-stream-9"
    config.vm.box_version = "9.0.48"
  end

  # Shared network config
  config.vm.network "private_network", ip: "192.168.56.12"

  # VMware provider config
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
  end
end
