Vagrant.configure("2") do |config|
  # Detect host CPU
  host_cpu = RbConfig::CONFIG['host_cpu']

  if host_cpu =~ /arm|aarch64/
    # Mac ARM
    config.vm.box = "jacobw/fedora35-arm64"
  else
    # Windows x86_64
    config.vm.box = "generic/fedora35"
  end

  # Shared network config
  config.vm.network "private_network", ip: "192.168.56.12"

  # VMware provider config
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
  end
end
